#!/bin/bash
# The logic to stop your application should be put in this script.
#kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
TMUX_SESSION="minecraft-volny"

WARNING_MESSAGE="Server is shutting down now!"
WARNING_SLEEP=3

tmux send -t $TMUX_SESSION "say $WARNING_MESSAGE" C-m
sleep $WARNING_SLEEP
tmux send -t $TMUX_SESSION "stop" C-m

#JAVAPID=`netstat -anp 2> /dev/null | grep $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT | awk '{ print $7 }' | sed 's/\/java$//'`

exit 0
